[build]
# Use Dockerfile to build the Python app with Playwright
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
# startCommand is defined in Dockerfile CMD
restartPolicyType = "ON_FAILURE"
healthcheckPath = "/"
healthcheckTimeout = 300

[variables]
PYTHONDONTWRITEBYTECODE = "1"
PYTHONUNBUFFERED = "1"

